trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Azure-Service-Connection'  # Use this exact name from your Service Connections
    repository: 'acrdccloudshoaibahmed/myapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure-Service-Connection'  # Match this to your existing service connection
    appName: 'acrdccloudshoaibahmed'
    containers: 'acrdccloudshoaibahmed.azurecr.io/myapp:latest'
