trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acrdccloudshoaibahmed'  # Use your ACR service connection name
    repository: 'acrdccloudshoaibahmed/myapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure-Subscription'  # Use the exact name of your ARM service connection
    appName: 'acrdccloudshoaibahmed'
    containers: 'acrdccloudshoaibahmed.azurecr.io/myapp:latest'
