trigger:
- main  # Adjust branch if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'  # Azure Container Registry
    repository: 'acrdccloudshoaibahmed/myapp'  # Modify accordingly
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '86d45bcc-ef4a-4a2b-beb4-88b06e7e2a8a'
    appName: 'app-dc-cloud-shoaibahmed'
    containers: 'acrdccloudshoaibahmed.azurecr.io/myapp:latest'
